# -*- coding: utf-8 -*-
"""MorphologicalProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6nDi6Pyf7fMHM64Cv14Stsd4b69coID
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img= cv2.imread("/content/Fig0911(a)(noisy_fingerprint).tif",0) # Read the image

plt.imshow(img, cmap="gray",vmin=0,vmax=255)
plt.title("Öriginal image")

#Erosion function without use of built in function
def erosion(img):
  s=int(input("Enter size of mask:"))
  SE=np.ones((s,s), dtype=np.uint8)
  const=(s-1)//2
  r,c=img.shape #storing rows and col of the image
  img_erode=np.zeros((r,c), dtype= np.uint8)
  for i in range(const, r-const):
   for j in range(const,c-const):
    temp= img[i-const:i+const+1, j-const:j+const+1]
    product= temp*SE
    img_erode[i,j]= np.min(product)
  return img_erode

#Dilation function without use of built in function
def dilation(img1):
 r1,c1=img1.shape
 SED= np.array([[1,1,1], [1,1,1], [1,1,1]])
 const1= 1
 img_dilute=np.zeros((r1,c1), dtype= np.uint8)
 for i in range(const1, r1-const1):
  for j in range(const1,c1-const1):
    temp= img1[i-const1:i+const1+1, j-const1:j+const1+1]
    product= temp*SED
    img_dilute[i,j]= np.max(product)
 return img_dilute

#Performing opening of image:erosion followed by dilation
img1=erosion(img)
img2=dilation(img1)

#Performing closing of image:dilation followed by erosion
img3=dilation(img2)
img4=erosion(img3)

plt.figure(figsize=(30,30))
plt.subplot(1,5,1)
plt.imshow(img, cmap="gray")
plt.title("Original")
plt.subplot(1,5,2)
plt.imshow(img1, cmap="gray")
plt.title("Erosion stage 1 ")
plt.subplot(1,5,3)
plt.imshow(img2, cmap="gray")
plt.title("Dilation stage 1 ")
plt.subplot(1,5,4)
plt.imshow(img3, cmap="gray")
plt.title("Dilation stage 2 ")
plt.subplot(1,5,5)
plt.imshow(img4, cmap="gray")
plt.title("Erosion stage 2 ")

! jupyter nbconvert --to html /content/I078_SIP_Prac9.ipynb

"""###Conclusion
Performed morphological opening and closing of an image. Erosion followed by dilation opens the image and dilation followed by erosion closes the image.

Imgae opening removes internal noise(spots on the image) from the image while closing smoothens the image. Ultimately,we obtain an smoothened image with no noise.
"""